# Generated by Django 2.2.28 on 2025-02-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0054_auto_20240426_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='consultation_type',
            field=models.SmallIntegerField(
                choices=[(1, 'Osteopathy'), (2, 'Laser'), (3, 'Micronutrition')],
                default=1,
                verbose_name='Consultation type',
            ),
        ),
    ]
